import {
  TARGET_LANGUAGE_OPTIONS,
  type UiLanguage,
} from "./app-settings";

const TEXT = {
  en: {
    appName: "Lucid Editor",
    header: {
      projects: "Projects",
      history: "History",
      settings: "Settings",
      help: "Help",
    },
    toolbar: {
      auto: "Auto",
      to: "to",
      paragraphs: "paragraphs",
      upload: "Upload .md",
      clear: "Clear",
      cancel: "Cancel",
      notConfigured: "No API Key",
      lazyMode: "Lazy",
      fullMode: "Full",
      translate: "Translate",
      translating: "Translating...",
    },
    splitView: {
      original: "Original",
      translation: "Translation",
      fileName: "Readme.md",
      placeholder: "Paste Markdown here, or drag & drop a .md file...",
      empty: "Paste Markdown below, or upload a .md file to start.",
      preview: "Preview",
      code: "Code",
      copy: "Copy",
      save: "Save",
    },
    input: {
      dropTitle: "Drop Markdown to import",
      dropDescription: "Supports .md, .markdown, and .txt files.",
      hint: "Drop .md anywhere or Ctrl+V paste",
      buffers: "Buffers",
      active: "Active",
    },
    statusBar: {
      title: "Translation Logs",
      retryFailed: "Retry failed",
      retrying: "Retrying...",
      ready: "Ready",
      translating: "Translating",
      connectionLost: "Connection Lost",
      waiting: "Waiting for Markdown input.",
      parsed: "Parsed {count} paragraph buffers.",
      translated: "{done}/{total} translated",
      inProgress: "{count} in progress",
      errors: "{count} errors",
      streamLost: "Stream connection lost.",
      applying: "Applying rendered Markdown output to buffers.",
      progress: "Progress",
    },
    paragraph: {
      translating: "Sync",
      error: "Error",
      edited: "Edit",
      retry: "Retry",
      retrying: "Retrying...",
      retranslate: "Re-translate",
    },
    settings: {
      title: "Settings",
      description: "Move core workspace preferences and provider configuration into one place.",
      general: "General",
      providers: "AI Providers",
      glossary: "Glossary",
      historyLink: "Open history",
      historyDescription: "History stays as a dedicated page for reviewing past translation runs.",
      appearanceTitle: "Workspace Preferences",
      appearanceDescription: "Set the default behavior for the editor and translation workflow.",
      themeMode: "Theme",
      themeModeDescription: "Theme changes apply immediately and auto-save.",
      themeSystem: "Follow System",
      themeLight: "Light",
      themeDark: "Dark",
      interfaceLanguage: "Interface Language",
      defaultTargetLanguage: "Default Translation Language",
      autoTranslate: "Auto Translate",
      autoTranslateDescription: "Start translation automatically after Markdown input changes.",
      debounce: "Debounce Delay",
      debounceDescription: "Delay before auto translation starts after input changes.",
      milliseconds: "ms",
      saveGeneral: "Save Settings",
      discardGeneral: "Discard Changes",
      themeSaved: "Theme updated.",
      themeSaveFailed: "Failed to update theme.",
      generalSaved: "Settings saved.",
      generalSaveFailed: "Failed to save settings.",
      sideDescription: "Choose a section",
      providersTitle: "Provider Configuration",
      providersDescription: "Configure API keys, endpoints, models, and connectivity tests.",
      addProvider: "Add Provider",
      glossaryTitle: "Glossary Management",
      glossaryDescription: "Manage project terminology without leaving Settings.",
      cacheTitle: "Translation Cache",
      cacheDescription:
        "Cached translations are reused automatically to avoid redundant API calls.",
      cacheClear: "Clear Cache",
      cacheClearing: "Clearing...",
      cacheEntries: "Cached Entries",
      cacheSize: "Approximate Size",
    },
    provider: {
      sectionTag: "Provider Config",
      configured: "Configured",
      notConfigured: "Not configured",
      providerName: "Provider Name",
      apiKey: "Api Key",
      apiKeyHint: "Edit the value directly to replace the saved Api key.",
      model: "Model",
      modelHint: "Model list is optional. You can always type a model manually.",
      baseUrl: "Base Url",
      baseUrlHint: "Provider icon is derived automatically from the Base Url domain.",
      fetchModels: "Fetch Models",
      fetchingModels: "Fetching...",
      testModel: "Test Model",
      testingModel: "Testing...",
      delete: "Delete",
      deleting: "Deleting...",
      save: "Save",
      saving: "Saving...",
      showApiKey: "Show Api key",
      hideApiKey: "Hide Api key",
      customTitle: "Custom Openai-Compatible Config",
      builtinTitle: "Openai Config",
      deleteConfirm: 'Delete provider "{name}"?',
      fetchedModels: "Fetched {count} models",
      fetchFailed: "Failed to fetch models",
      modelPassed: "Model test passed",
      modelFailed: "Model test failed",
      saveFailed: "Failed to save config",
      deleteFailed: "Failed to delete provider",
      relayPlaceholder: "Relay Api",
      customBaseUrlPlaceholder: "https://relay.example.com/v1",
    },
    glossary: {
      tag: "terms",
      title: "Glossary",
      description: "Manage real translation terminology from your local database. Enabled terms act as your project-level source of truth.",
      add: "Add New Term",
      allTerms: "All Terms",
      enabled: "Enabled",
      disabled: "Disabled",
      search: "Search by term or translation...",
      allSourceLangs: "All source langs",
      allTargetLangs: "All target langs",
      originalTerm: "Original Term",
      translatedTerm: "Translated Term",
      languagePair: "Language Pair",
      note: "Note",
      status: "Status",
      actions: "Actions",
      noNote: "No note",
      editTerm: "Edit Term",
      addTerm: "Add New Term",
      sourceTerm: "Source Term",
      targetTerm: "Translated Term",
      sourceLang: "Source Lang",
      targetLang: "Target Lang",
      enableTerm: "Enable this term for active translation",
      cancel: "Cancel",
      createTerm: "Create Term",
      saveChanges: "Save Changes",
      loading: "Loading glossary terms...",
      emptyTitle: "No glossary terms found",
      emptyDescription: "Adjust the current filters or create the first project term.",
      requiredTerms: "Source and translated terms are required",
      requiredLangs: "Source and target languages are required",
      saveFailed: "Failed to save glossary term",
      deleteFailed: "Failed to delete glossary term",
      toggleFailed: "Failed to update glossary status",
      downloadTemplate: "Download Template",
      importCsv: "Import CSV",
      importingCsv: "Importing...",
      importReadFailed: "Failed to read CSV file",
      importFailed: "Failed to import glossary CSV",
      importSummary: "Imported {inserted} terms, skipped {skipped} rows.",
      importSummaryNoSkipped: "Imported {inserted} terms.",
      importErrorsTitle: "{count} rows need attention.",
      importRowLabel: "Row {row}",
      importFormatStage: "Format",
      importValidationStage: "Validation",
      importDbStage: "Database",
      deleteConfirm: 'Delete glossary term "{name}"?',
      editAction: "Edit term",
      disableAction: "Disable term",
      enableAction: "Enable term",
      deleteAction: "Delete term",
      embeddedTitle: "Project Glossary",
      embeddedDescription: "Search, filter, and maintain terminology within the Settings workspace.",
    },
    history: {
      visibleTasks: "visible tasks",
      title: "Translation History",
      description: "Monitor real translation runs stored in the local task history and inspect engine, language, timing, and processing outcomes.",
      search: "Search by task id, engine, or language...",
      searchButton: "Search",
      totalTasks: "Total Tasks",
      completed: "Completed",
      successRate: "Success Rate",
      all: "All",
      inProgress: "In Progress",
      issues: "Issues",
      task: "Task",
      targetLanguage: "Target Language",
      engine: "Engine",
      created: "Created",
      progress: "Progress",
      status: "Status",
      actions: "Actions",
      selectAll: "Select all tasks",
      selectedCount: "{count} selected",
      delete: "Delete",
      deleteTask: "Delete task",
      deleteSelected: "Delete selected",
      deleteFiltered: "Delete current results",
      deleteTaskConfirm: 'Delete task "{id}" from history?',
      deleteSelectedConfirm: "Delete {count} selected tasks from history?",
      deleteFilteredConfirm: "Delete all {count} tasks in the current results?",
      deleteFailed: "Failed to delete history tasks",
      deleteSuccess: "Deleted {count} history tasks.",
      deleting: "Deleting...",
      confirmDelete: "Delete",
      cancel: "Cancel",
      noResultsTitle: "No history results found",
      noResultsDescription: "Adjust the current search or status filter to inspect other tasks.",
    },
  },
  "zh-CN": {
    appName: "Lucid Editor",
    header: {
      projects: "项目",
      history: "历史",
      settings: "设置",
      help: "帮助",
    },
    toolbar: {
      auto: "自动",
      to: "到",
      paragraphs: "段落",
      upload: "上传 .md",
      clear: "清空",
      translate: "开始翻译",
      translating: "翻译中...",
    },
    splitView: {
      original: "原文",
      translation: "译文",
      fileName: "Readme.md",
      placeholder: "在这里粘贴 Markdown，或拖拽一个 .md 文件...",
      empty: "在下方粘贴 Markdown，或上传一个 .md 文件开始。",
      preview: "预览",
      code: "代码",
      copy: "复制",
      save: "保存",
    },
    input: {
      dropTitle: "拖放 Markdown 以导入",
      dropDescription: "支持 .md、.markdown 和 .txt 文件。",
      hint: "任意位置拖入 .md 或按 Ctrl+V 粘贴",
      buffers: "缓冲区",
      active: "已激活",
    },
    statusBar: {
      title: "翻译日志",
      retryFailed: "重试失败项",
      retrying: "重试中...",
      ready: "就绪",
      connectionLost: "连接中断",
      waiting: "等待 Markdown 输入。",
      parsed: "已解析 {count} 个段落缓冲区。",
      translated: "已翻译 {done}/{total}",
      inProgress: "{count} 个进行中",
      errors: "{count} 个错误",
      streamLost: "流式连接已中断。",
      applying: "正在将渲染后的 Markdown 输出写回缓冲区。",
      progress: "进度",
    },
    paragraph: {
      translating: "同步中",
      error: "错误",
      edited: "已编辑",
      retry: "重试",
      retrying: "重试中...",
    },
    settings: {
      title: "设置",
      description: "把核心工作区偏好和供应商配置集中到一个页面管理。",
      general: "常规",
      providers: "AI 供应商",
      glossary: "术语库",
      historyLink: "打开历史页",
      historyDescription: "历史页保持独立页面，用于查看以往翻译任务。",
      appearanceTitle: "工作区偏好",
      appearanceDescription: "设置编辑器和翻译流程的默认行为。",
      interfaceLanguage: "界面语言",
      defaultTargetLanguage: "默认翻译语言",
      autoTranslate: "自动翻译",
      autoTranslateDescription: "Markdown 输入发生变化后自动开始翻译。",
      debounce: "防抖延迟",
      debounceDescription: "输入变化后，自动翻译启动前的等待时间。",
      milliseconds: "毫秒",
      saveGeneral: "保存设置",
      discardGeneral: "放弃更改",
      generalSaved: "设置已保存。",
      generalSaveFailed: "保存设置失败。",
      sideDescription: "选择一个设置分区",
      providersTitle: "供应商配置",
      providersDescription: "配置 API Key、接口地址、模型和连通性测试。",
      addProvider: "新增供应商",
      glossaryTitle: "术语管理",
      glossaryDescription: "在设置页内直接维护项目术语。",
    },
    provider: {
      sectionTag: "供应商配置",
      configured: "已配置",
      notConfigured: "未配置",
      providerName: "供应商名称",
      apiKey: "Api Key",
      apiKeyHint: "直接编辑即可替换已保存的 Api key。",
      model: "模型",
      modelHint: "模型列表是可选的，也可以手动输入模型名。",
      baseUrl: "Base Url",
      baseUrlHint: "供应商图标会根据 Base Url 的域名自动推导。",
      fetchModels: "获取模型",
      fetchingModels: "获取中...",
      testModel: "测试模型",
      testingModel: "测试中...",
      delete: "删除",
      deleting: "删除中...",
      save: "保存",
      saving: "保存中...",
      showApiKey: "显示 Api key",
      hideApiKey: "隐藏 Api key",
      customTitle: "自定义 Openai 兼容配置",
      builtinTitle: "Openai 配置",
      deleteConfirm: '确定删除供应商“{name}”？',
      fetchedModels: "已获取 {count} 个模型",
      fetchFailed: "获取模型失败",
      modelPassed: "模型测试通过",
      modelFailed: "模型测试失败",
      saveFailed: "保存配置失败",
      deleteFailed: "删除供应商失败",
      relayPlaceholder: "Relay Api",
      customBaseUrlPlaceholder: "https://relay.example.com/v1",
    },
    glossary: {
      tag: "术语",
      title: "术语库",
      description: "管理本地数据库中的真实翻译术语。启用后的术语会作为项目级术语基准。",
      add: "新增术语",
      allTerms: "全部术语",
      enabled: "已启用",
      disabled: "已禁用",
      search: "按术语或译文搜索...",
      allSourceLangs: "全部源语言",
      allTargetLangs: "全部目标语言",
      originalTerm: "原术语",
      translatedTerm: "译文术语",
      languagePair: "语言对",
      note: "备注",
      status: "状态",
      actions: "操作",
      noNote: "无备注",
      editTerm: "编辑术语",
      addTerm: "新增术语",
      sourceTerm: "源术语",
      targetTerm: "译文术语",
      sourceLang: "源语言",
      targetLang: "目标语言",
      enableTerm: "启用该术语参与翻译",
      cancel: "取消",
      createTerm: "创建术语",
      saveChanges: "保存修改",
      loading: "正在加载术语...",
      emptyTitle: "没有匹配的术语",
      emptyDescription: "调整筛选条件，或创建第一条项目术语。",
      requiredTerms: "源术语和译文术语不能为空",
      requiredLangs: "源语言和目标语言不能为空",
      saveFailed: "保存术语失败",
      deleteFailed: "删除术语失败",
      toggleFailed: "更新术语状态失败",
      deleteConfirm: '确定删除术语“{name}”？',
      editAction: "编辑术语",
      disableAction: "禁用术语",
      enableAction: "启用术语",
      deleteAction: "删除术语",
      embeddedTitle: "项目术语库",
      embeddedDescription: "直接在设置页内搜索、筛选和维护术语。",
    },
    history: {
      visibleTasks: "个可见任务",
      title: "翻译历史",
      description: "查看保存在本地任务历史中的真实翻译记录，并检查引擎、语言、时间和处理结果。",
      search: "按任务 id、引擎或语言搜索...",
      searchButton: "搜索",
      totalTasks: "任务总数",
      completed: "已完成",
      successRate: "成功率",
      all: "全部",
      inProgress: "进行中",
      issues: "异常",
      task: "任务",
      targetLanguage: "目标语言",
      engine: "引擎",
      created: "创建时间",
      progress: "进度",
      status: "状态",
      noResultsTitle: "没有找到历史记录",
      noResultsDescription: "调整当前搜索或状态筛选以查看其他任务。",
    },
  },
} as const;

const mutableText = TEXT as unknown as {
  "zh-CN": {
    settings: Record<string, string>;
  };
};

Object.assign(mutableText["zh-CN"].settings, {
  themeMode: "\u4e3b\u9898",
  themeModeDescription:
    "\u4e3b\u9898\u5207\u6362\u4f1a\u7acb\u5373\u751f\u6548\u5e76\u81ea\u52a8\u4fdd\u5b58\u3002",
  themeSystem: "\u8ddf\u968f\u7cfb\u7edf",
  themeLight: "\u6d45\u8272",
  themeDark: "\u6df1\u8272",
  themeSaved: "\u4e3b\u9898\u5df2\u66f4\u65b0\u3002",
  themeSaveFailed: "\u66f4\u65b0\u4e3b\u9898\u5931\u8d25\u3002",
  cacheTitle: "\u7ffb\u8bd1\u7f13\u5b58",
  cacheDescription:
    "\u7f13\u5b58\u7684\u7ffb\u8bd1\u4f1a\u88ab\u81ea\u52a8\u590d\u7528\uff0c\u4ee5\u907f\u514d\u91cd\u590d\u7684 API \u8c03\u7528\u3002",
  cacheClear: "\u6e05\u7a7a\u7f13\u5b58",
  cacheClearing: "\u6e05\u7406\u4e2d...",
  cacheEntries: "\u7f13\u5b58\u6761\u76ee",
  cacheSize: "\u9884\u4f30\u5927\u5c0f",
});

Object.assign((mutableText["zh-CN"] as Record<string, unknown>).toolbar as Record<string, string>, {
  cancel: "\u53d6\u6d88",
  notConfigured: "\u672a\u914d\u7f6e API Key",
  lazyMode: "\u6309\u9700",
  fullMode: "\u5168\u91cf",
});

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).paragraph as Record<string, string>,
  {
    retranslate: "\u91cd\u65b0\u7ffb\u8bd1",
  }
);

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).provider as Record<string, string>,
  {
    saved: "保存配置成功",
  }
);

Object.assign((TEXT as unknown as { en: { provider: Record<string, string> } }).en.provider, {
  saved: "Config saved.",
});

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).provider as Record<string, string>,
  {
    deleted: "鍒犻櫎渚涘簲鍟嗘垚鍔?",
  }
);

Object.assign((TEXT as unknown as { en: { provider: Record<string, string> } }).en.provider, {
  deleted: "Provider deleted.",
});

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).glossary as Record<string, string>,
  {
    downloadTemplate: "\u4e0b\u8f7d\u6a21\u677f",
    importCsv: "\u6279\u91cf\u5bfc\u5165",
    importingCsv: "\u5bfc\u5165\u4e2d...",
    importReadFailed: "\u8bfb\u53d6 CSV \u6587\u4ef6\u5931\u8d25",
    importFailed: "\u5bfc\u5165\u672f\u8bed CSV \u5931\u8d25",
    importSummary: "\u6210\u529f\u5bfc\u5165 {inserted} \u6761\uff0c\u8df3\u8fc7 {skipped} \u884c\u3002",
    importSummaryNoSkipped: "\u6210\u529f\u5bfc\u5165 {inserted} \u6761\u3002",
    importErrorsTitle: "\u6709 {count} \u884c\u9700\u8981\u5904\u7406\u3002",
    importRowLabel: "\u7b2c {row} \u884c",
    importFormatStage: "\u683c\u5f0f",
    importValidationStage: "\u6821\u9a8c",
    importDbStage: "\u5199\u5165",
  }
);

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).statusBar as Record<string, string>,
  {
    translating: "\u7ffb\u8bd1\u4e2d",
  }
);

Object.assign(
  (mutableText["zh-CN"] as Record<string, unknown>).history as Record<string, string>,
  {
    actions: "\u64cd\u4f5c",
    selectAll: "\u5168\u9009\u5f53\u524d\u4efb\u52a1",
    selectedCount: "\u5df2\u9009 {count} \u9879",
    delete: "\u5220\u9664",
    deleteTask: "\u5220\u9664\u4efb\u52a1",
    deleteSelected: "\u5220\u9664\u5df2\u9009",
    deleteFiltered: "\u5220\u9664\u5f53\u524d\u7ed3\u679c",
    deleteTaskConfirm:
      "\u786e\u5b9a\u4ece\u5386\u53f2\u8bb0\u5f55\u4e2d\u5220\u9664\u4efb\u52a1 \"{id}\" \u5417\uff1f",
    deleteSelectedConfirm:
      "\u786e\u5b9a\u4ece\u5386\u53f2\u8bb0\u5f55\u4e2d\u5220\u9664\u5df2\u9009\u7684 {count} \u6761\u4efb\u52a1\u5417\uff1f",
    deleteFilteredConfirm:
      "\u786e\u5b9a\u5220\u9664\u5f53\u524d\u7ed3\u679c\u4e2d\u7684 {count} \u6761\u4efb\u52a1\u5417\uff1f",
    deleteFailed: "\u5220\u9664\u5386\u53f2\u8bb0\u5f55\u5931\u8d25",
    deleteSuccess: "\u5df2\u5220\u9664 {count} \u6761\u5386\u53f2\u8bb0\u5f55\u3002",
    deleting: "\u5220\u9664\u4e2d...",
    confirmDelete: "\u5220\u9664",
    cancel: "\u53d6\u6d88",
  }
);

export function getUiText(language: UiLanguage) {
  return TEXT[language];
}

export function formatUiText(
  template: string,
  values: Record<string, string | number>
) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? ""));
}

export function getTargetLanguageOptions(language: UiLanguage) {
  const zhLabels: Record<string, string> = {
    en: "英语",
    "zh-CN": "简体中文",
    "zh-TW": "繁体中文",
    ja: "日语",
    ko: "韩语",
  };

  return TARGET_LANGUAGE_OPTIONS.map((option) => ({
    ...option,
    label: language === "zh-CN" ? zhLabels[option.value] || option.label : option.label,
  }));
}
